version: '3'
services:
  network_manager:
    image: frogoman/network_manager:latest
    container_name: network_manager
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DOCKER_HOST={IP_TO_DOCKER_MACHINE}